language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
sudo: false
cache:
  directories:
    - $HOME/.cache/pip
# commands to install dependencies
install: 
  # Get newer pip and whell for binary caching support
  - pip install --upgrade pip wheel
  # Python-ldap will get a release for python3
  - if [ $( echo "$TRAVIS_PYTHON_VERSION > 3.3" | bc) -eq 1 ] ; then sed -i 's/python-ldap/#python-ldap/' requirements.txt; fi
  - pip install -r requirements-test.txt
# commands to run tests
script: 
  - py.test --cov=suseapi
  - pep8 suseapi
  - pylint --reports=n --rcfile=pylint.rc suseapi
  - pyflakes suseapi
after_script:
  - coveralls
  - ocular --data-file ".coverage" --config-file ".coveragerc"
  - coverage xml
  - python-codacy-coverage -r coverage.xml
  - codecov
cache:
  pip: true
